<?php

class ETC_CmsBlockquotes_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_blockquotes';
    protected $title = 'BlockQuotes';
    protected $icon = 'eicon-blockquote';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/frame\/wp-content\/themes\/fastway\/elementor\/templates\/widgets\/cms_blockquotes\/layout1.png"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/frame\/wp-content\/themes\/fastway\/elementor\/templates\/widgets\/cms_blockquotes\/layout2.png"},"3":{"label":"Layout 3","image":"http:\/\/localhost\/frame\/wp-content\/themes\/fastway\/elementor\/templates\/widgets\/cms_blockquotes\/layout3.png"}}}]},{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"title_text","label":"Title","type":"text","default":"Block Quote Title"},{"name":"content_text","label":"Content","type":"textarea","rows":10,"default":"Block Quote Content"}]},{"name":"section_style_content","label":"Content","tab":"style","controls":[{"name":"blockquotes_style","label":"Wrapper","type":"heading","separator":"before"},{"name":"blockquotes_background_color","label":"Background Color","type":"color","size_units":["px","%"],"selectors":{"{{WRAPPER}} .cms-blockquotes-wrapper blockquote":"background-color: {{VALUE}};"}},{"name":"blockquotes_padding","label":"Padding","type":"dimensions","size_units":["px"],"control_type":"responsive","selectors":{"{{WRAPPER}} .cms-blockquotes-wrapper blockquote":"padding: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"}},{"name":"title_style","label":"Title","type":"heading","separator":"before"},{"name":"title_bottom_space","label":"Spacing","type":"slider","size_units":["px"],"control_type":"responsive","range":{"px":{"min":0,"max":100}},"selectors":{"{{WRAPPER}} .blockquotes-title":"margin-top: {{SIZE}}{{UNIT}};"}},{"name":"title_color","label":"Color","type":"color","size_units":["px","%"],"selectors":{"{{WRAPPER}} .blockquotes-title":"color: {{VALUE}};"}},{"name":"title_typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .blockquotes-title"},{"name":"content_style","label":"Content","type":"heading","separator":"before"},{"name":"content_color","label":"Color","type":"color","size_units":["px","%"],"selectors":{"{{WRAPPER}} .blockquotes-content":"color: {{VALUE}};"}},{"name":"content_typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .blockquotes-content"}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}