<?php

class ETC_CmsImageCarousel_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_image_carousel';
    protected $title = 'CMS Images Carousel';
    protected $icon = 'eicon-slider-push';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"section_slick_slider_settings","label":"Carousel Settings","tab":"settings","controls":[{"name":"slide_mode","label":"Slide mode","type":"select","options":{"true":"Fade","false":"Slide"},"default":"false"},{"name":"slides_to_show","label":"Slides to Show","type":"select","control_type":"responsive","default":"","options":{"":"Default","1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10}},{"name":"slides_to_scroll","label":"Slides to Scroll","type":"select","control_type":"responsive","default":"","options":{"":"Default","1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10},"condition":{"slides_to_show!":"1"}},{"name":"slides_gutter","label":"Gutter","type":"number","default":30,"condition":{"slides_to_show!":"1"}},{"name":"arrows","label":"Show Arrows","type":"switcher","control_type":"responsive"},{"name":"arrows_pos","label":"Arrows Position","type":"select","control_type":"responsive","default":"in-vertical","options":{"in-vertical":"Inside Vertical","out-vertical":"Outside Vertical"},"condition":{"arrows":"true"},"prefix_class":"cms-slick-nav-","separator":"before"},{"name":"dots","label":"Show Dots","type":"switcher","control_type":"responsive","default":"true"},{"name":"dots_pos","label":"Dots Position","type":"select","control_type":"responsive","default":"out","options":{"in":"Inside","out":"Outside"},"condition":{"dots":"true"},"prefix_class":"cms-slick-dots-","separator":"before"},{"name":"pause_on_hover","label":"Pause on Hover","type":"switcher"},{"name":"autoplay","label":"Autoplay","type":"switcher"},{"name":"autoplay_speed","label":"Autoplay Speed","type":"number","default":5000,"condition":{"autoplay":"true"}},{"name":"infinite","label":"Infinite Loop","type":"switcher"},{"name":"speed","label":"Animation Speed","type":"number","default":500}],"condition":[]},{"name":"layout_section","label":"Layout","tab":"layout","prefix_class":"cms-image-carousel","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/elementor\/templates\/widgets\/cms_image_carousel\/layout\/layout1.png"}}}]},{"name":"source_section","label":"Galleries","tab":"content","controls":[{"name":"galleries","type":"gallery","control_type":"responsive","default":[],"dynamic":{"active":true}},{"name":"thumbnail","type":"image-size","control_type":"group","default":"large"}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'jquery-slick','cms-slick-slider' );
}