<?php

class ETC_CmsPiecharts_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_piecharts';
    protected $title = 'Pie Charts';
    protected $icon = 'fa fa-pie-chart';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/assets\/images\/elementor\/1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/assets\/images\/elementor\/2.jpg"}}}]},{"name":"section_piecharts","label":"Piecharts","tab":"content","controls":[{"name":"per_line","label":"Piecharts per row","type":"number","min":1,"max":5,"step":1,"default":4},{"name":"piecharts","label":"PieCharts","type":"repeater","controls":[{"name":"stats_title","label":"Stats Title","type":"text","label_block":true,"default":"Stats Title"},{"name":"percentage_value","label":"Percentage Value","type":"number","min":1,"max":100,"step":1,"default":30}],"default":[{"stats_title":"Web Design","percentage_value":87},{"stats_title":"SEO Services","percentage_value":76},{"stats_title":"WordPress Development","percentage_value":90},{"stats_title":"Brand Marketing","percentage_value":40}],"title_field":"{{{ stats_title }}}"}]},{"name":"section_styling","label":"Piechart Styling","tab":"style","controls":[{"name":"bar_color","label":"Bar color","type":"color","default":"#666666"},{"name":"track_color","label":"Track color","type":"color","default":"#dddddd"}]},{"name":"section_stats_title","label":"Stats Title","tab":"style","controls":[{"name":"stats_title_color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .cms-piecharts .piechart .label":"color: {{VALUE}};"}},{"name":"stats_title_typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .cms-piecharts .piechart .label"}]},{"name":"section_stats_percentage","label":"Stats Percentage","tab":"style","controls":[{"name":"stats_percentage_color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .cms-piecharts .piechart .percentage span":"color: {{VALUE}};"}},{"name":"stats_percentage_typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .cms-piecharts .piechart .percentage span"}]},{"name":"section_stats_percentage_symbol","label":"Stats Percentage Symbol","tab":"style","controls":[{"name":"stats_percentage_symbol_color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .cms-piecharts .piechart .percentage span sup":"color: {{VALUE}};"}},{"name":"stats_percentage_symbol_typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .cms-piecharts .piechart .percentage span sup"}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'easy-pie-chart-lib-js','cms-piecharts-widget-js' );
}