<?php

class ETC_CmsImageGallery_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_image_gallery';
    protected $title = 'CMS Image Gallery';
    protected $icon = 'eicon-gallery-grid';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"img_list","label":"Images Galleries","tab":"content","controls":[{"name":"galleries","label":"Add Item","type":"repeater","controls":[{"name":"title","label":"Title","type":"text","label_block":true},{"name":"filter_tag","label":"Filter Tag","description":"Enter tag for filter, multi tag separate by comma (,)","type":"text","label_block":true},{"name":"image","label":"Image","type":"media","label_block":true}],"default":[{"title":"Name #1","filter_tag":"cargo","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/images\/assets\/placeholder\/no-image.jpg"},{"title":"Name #2","filter_tag":"logistic","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/images\/assets\/placeholder\/no-image.jpg"},{"title":"Name #3","filter_tag":"storage","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/images\/assets\/placeholder\/no-image.jpg"},{"title":"Name #4","filter_tag":"trucking","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/images\/assets\/placeholder\/no-image.jpg"},{"title":"Name #5","filter_tag":"warehousing","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/images\/assets\/placeholder\/no-image.jpg"},{"title":"Name #6","filter_tag":"cargo","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/images\/assets\/placeholder\/no-image.jpg"},{"title":"Name #7","filter_tag":"logistic","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/images\/assets\/placeholder\/no-image.jpg"},{"title":"Name #8","filter_tag":"storage","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/images\/assets\/placeholder\/no-image.jpg"},{"title":"Name #9","filter_tag":"trucking","image":"http:\/\/localhost\/fastway\/wp-content\/themes\/fastway\/images\/assets\/placeholder\/no-image.jpg"}],"title_field":"{{{ title }}}"}]},{"name":"layout_section","label":"Image Settings","tab":"layout","controls":[{"name":"thumbnail","type":"image-size","control_type":"group","default":"full"},{"name":"col_sm","label":"Columns SM Devices","type":"select","default":"2","options":{"1":"1","2":"2","3":"3","4":"4","6":"6","12":"12"}},{"name":"col_md","label":"Columns MD Devices","type":"select","default":"3","options":{"1":"1","2":"2","3":"3","4":"4","6":"6","12":"12"}},{"name":"col_lg","label":"Columns LG Devices","type":"select","default":"4","options":{"1":"1","2":"2","3":"3","4":"4","6":"6","12":"12"}},{"name":"col_xl","label":"Columns XL Devices","type":"select","default":"4","options":{"1":"1","2":"2","3":"3","4":"4","6":"6","12":"12"}},{"name":"open_lightbox","label":"Lightbox","type":"select","default":"yes","options":{"yes":"Yes","no":"No"}},{"name":"gallery_link","label":"Link","type":"select","default":"file","options":{"file":"Media File","attachment":"Attachment Page"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'imagesloaded','isotope','cms-masonry' );
}